apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
spec:
  accessModes:
    - ReadWriteOnce # ReadWriteOnce, ReadOnlyMany, ReadWriteMany
  resources:
    requests:
      storage: 10Gi # 10Gb
