apiVersion: apps/v1 
kind: Deployment
metadata:
  name: my-web-deploy
  labels:
    version: "v1.2.0"  
  namespace: production  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.4  
